//Pantalla Inicio 
export const PRODUCTO_LISTA_REQUEST = 'PRODUCTO_LISTA_REQUEST'
export const PRODUCTO_LISTA_SUCCESS = 'PRODUCTO_LISTA_SUCCESS'
export const PRODUCTO_LISTA_FAIL = 'PRODUCTO_LISTA_FAIL'

//Pantalla Producto Individual
export const PRODUCTO_DETALLES_REQUEST = 'PRODUCTO_DETALLES_REQUEST'
export const PRODUCTO_DETALLES_SUCCESS = 'PRODUCTO_DETALLES_SUCCESS'
export const PRODUCTO_DETALLES_FAIL = 'PRODUCTO_DETALLES_FAIL'

