export const USUARIO_REGISTRO_REQUEST = 'USUARIO_REGISTRO_REQUEST'
export const USUARIO_REGISTRO_SUCCESS = 'USUARIO_REGISTRO_SUCCESS'
export const USUARIO_REGISTRO_FAIL = 'USUARIO_REGISTRO_FAIL'
export const USUARIO_DESCONECTADO = 'USUARIO_DESCONECTADO'